-- Automated BEO Generator — event_orders table
-- Catering By Wendy — 2026-04-28
--
-- Stores every BEO generated by the /logistics/beo-generator route.
-- This is the audit trail of all quotes and event orders sent.
-- All cost, menu, equipment, and timeline data is captured at generation
-- time so historical BEOs remain accurate even after price changes.

CREATE TABLE IF NOT EXISTS public.event_orders (
  -- Identity
  id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  beo_number          TEXT          NOT NULL UNIQUE,   -- e.g. "BEO-2026-000042"
  status              TEXT          NOT NULL DEFAULT 'draft',  -- draft | sent | accepted | cancelled

  -- Event details
  event_name          TEXT          NOT NULL,
  event_date          DATE,
  service_time        TEXT,                            -- "18:00" (24-h)
  venue_name          TEXT,
  venue_zip           TEXT,
  service_style       TEXT          NOT NULL DEFAULT 'plated', -- plated | buffet | cocktail
  guest_count         INT           NOT NULL,
  special_instructions TEXT,

  -- Recipes selected (IDs + names snapshotted at generation time)
  recipe_ids          TEXT[]        NOT NULL DEFAULT '{}',
  recipe_names        TEXT[]        NOT NULL DEFAULT '{}',

  -- Financial summary
  cogs_total          NUMERIC(10,2) NOT NULL DEFAULT 0,
  labor_cost          NUMERIC(10,2) NOT NULL DEFAULT 0,
  equipment_cost      NUMERIC(10,2) NOT NULL DEFAULT 0,
  overhead_cost       NUMERIC(10,2) NOT NULL DEFAULT 0,
  subtotal            NUMERIC(10,2) NOT NULL DEFAULT 0,
  tax_rate            NUMERIC(6,4)  NOT NULL DEFAULT 0.08,
  tax_amount          NUMERIC(10,2) NOT NULL DEFAULT 0,
  total               NUMERIC(10,2) NOT NULL DEFAULT 0,
  per_person_rate     NUMERIC(10,2) NOT NULL DEFAULT 0,

  -- Full document snapshots (JSONB for flexibility)
  itemized_menu       JSONB,   -- [{recipeName, ingredients:[{name,qty,unit,marketRate,cost}], recipeCOGS}]
  equipment_needs     JSONB,   -- [{item,qty,unit,rentalCostPerUnit,totalRentalCost,category}]
  run_of_show         JSONB,   -- [{time,task,owner,isKeyMoment}]
  market_rate_snapshot JSONB,  -- [{item_name,price_per_unit,unit,competitor_name,captured_at}] used at generation

  -- Metadata
  generated_by        TEXT,    -- subscriber_profiles.id
  notes               TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_event_orders_status
  ON public.event_orders(status);
CREATE INDEX IF NOT EXISTS idx_event_orders_event_date
  ON public.event_orders(event_date DESC);
CREATE INDEX IF NOT EXISTS idx_event_orders_created
  ON public.event_orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_event_orders_beo_number
  ON public.event_orders(beo_number);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_event_orders_updated_at
  BEFORE UPDATE ON public.event_orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Row Level Security (open policy — same as other tables in this project)
ALTER TABLE public.event_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "event_orders_service_all"
  ON public.event_orders FOR ALL USING (true) WITH CHECK (true);
